name: push to hatena blog

on: 
  push:
    branches-ignore:
      - master

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

    - name: Download blogsync
      run: |
        curl -L https://github.com/x-motemen/blogsync/releases/download/v0.12.3/blogsync_v0.12.3_linux_amd64.tar.gz > a.tar.gz
        tar xvfz a.tar.gz
        mv blogsync_v0.12.3_linux_amd64/blogsync /tmp/blogsync
        chmod +x /tmp/blogsync

    - uses: actions/checkout@v3

    - name: Fetch base branch
      run: git fetch origin master

    - name: Sync
      env:
        BSY: ${{ secrets.BSY }}
      run: |
        pwd
        echo -e ${BSY}
        echo -e ${BSY} > blogsync.yaml
        git diff origin/master  --name-only| egrep "entries/.+.md$" | xargs -t -n1 /tmp/blogsync push

